spring:
  datasource:
    username: ala
    password: ala
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gestion_des_federation
  application:
    name: platfromeDeGestionDesFederatioSportives
  mail:
    host: localhost
    port: 1025
    username: ala
    password: ala
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 500
        timeout: 3000
        writetimeout: 5000



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


application:
  security:
    jwt:
      secret-key: yhwdxGYjqMr3qRBFFxF3l7si5Q9PfetGI1TD0t4sl06ksSdvyhgLss8YL066tJsZ
      expiration : 8640000
  mail:
    activation-url: http://localhost/4200/activation-account
    login-url: http://localhost/4200/login
  file:
    upload:
      photos-output-path: ./uploads


