services:
  postgres:
    container_name: postgres-sql-platform-sportive
    image: postgres
    environment:
      POSTGRES_USER: ala
      POSTGRES_PASSWORD: ala
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: gestion_des_federation
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - app-network

  java-mailer:
    container_name: java-mailer-platform-sportive
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    restart: unless-stopped


networks:
  app-network:
    driver: bridge

volumes:
  postgres:
    driver: local
